theme       : jekyll-theme-slate
title       : "Pk11"
description : "Pk11's site"
repo        : "epicpkmn11/epicpkmn11.github.io"
color       : "#f2acae"

defaults:
  -
    values:
      layout: "default"
      title: "Pk11"