theme       : jekyll-theme-slate
title       : "Pk11"
description : "Pk11's site"
repo        : "epicpkmn11/epicpkmn11.github.io"
color       : "#f2acae"
markdown_ext        : "markdown,mkdown,mkdn,mkd,md,html"

defaults:
  -
    values:
      layout: "default"
      title: "Pk11"
      image: "/assets/images/pfp/pk11-1.png"